services:
  mongodb:
   image: mongo
   container_name: mongo_db
   ports:
     - 27017:27017
   volumes:
     - mongo:/data
   environment:
      - MONGO_INITDB_ROOT_USERNAME=abdo
      - MONGO_INITDB_ROOT_PASSWORD=abdo    
   
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=abdo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abod
      - ME_CONFIG_MONGODB_SERVER=mongodb  
    
   